const text = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. In orci sapien, faucibus eget mi auctor, elementum imperdiet neque. Sed semper iaculis dignissim. Duis accumsan eget turpis ut semper. Pellentesque hendrerit cursus tortor, at elementum turpis eleifend ac. Morbi in tortor ipsum. Aliquam tempor, sapien quis molestie maximus, orci libero eleifend quam, quis elementum lectus metus sit amet arcu. Donec purus elit, sodales id massa non, commodo imperdiet libero. Maecenas vulputate elit gravida sagittis lobortis. Etiam ullamcorper sapien vel ipsum hendrerit aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus lobortis ex ut pulvinar consequat. Maecenas sollicitudin orci quis tincidunt gravida. Etiam rhoncus arcu ac eros semper eleifend. Suspendisse id leo tellus.
Pellentesque in mollis turpis, nec tempus diam. Nulla congue lacinia nibh. Curabitur sit amet lorem tellus. Suspendisse lorem dui, condimentum sit amet porta id, dictum et dui. Nam tempor egestas pellentesque. Praesent sollicitudin dui vel lacus efficitur consectetur. Vivamus nec laoreet ante. Phasellus egestas viverra venenatis. Integer id lacinia ligula, eu molestie nunc. Suspendisse at faucibus nibh. Cras vitae fringilla lectus, id ullamcorper nibh. Nullam nibh velit, commodo eu viverra non, porttitor et justo. Vestibulum facilisis hendrerit tempus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean sed est ultricies, lacinia augue ut, vestibulum massa. Praesent id magna congue, ultricies lorem nec, facilisis turpis.
Suspendisse suscipit massa eu nisl aliquam, sit amet consectetur nibh feugiat. Nunc ac feugiat justo. Ut molestie mattis orci, eu sagittis neque. Curabitur eros dolor, facilisis non interdum vitae, mattis a ante. Nam id augue sed eros condimentum efficitur non in erat. Suspendisse efficitur felis sed eros finibus finibus. Donec eu rutrum nibh. Maecenas egestas, magna ut posuere mollis, tortor sem feugiat risus, sed imperdiet turpis nisi et libero. Integer gravida, lacus sit amet convallis mollis, ante augue pretium est, sit amet finibus sem sapien id augue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi pulvinar est massa, nec cursus lacus dignissim sit amet. Pellentesque quis tellus eu urna posuere porttitor.
Aliquam venenatis tortor nec facilisis fermentum. Cras placerat, nunc ac interdum dapibus, ex nisl feugiat tellus, in porttitor enim tortor ut felis. Aenean dignissim tincidunt turpis, finibus vestibulum enim facilisis a. Donec mattis tortor ex, id eleifend turpis congue a. Aenean a metus eros. Fusce libero quam, tristique quis quam vitae, tempus mollis nisl. Integer efficitur mi non purus tincidunt, quis semper tellus imperdiet. Nulla non gravida est. Morbi leo sapien, placerat in pharetra non, fermentum a augue. Nunc pellentesque lectus nec neque congue eleifend. Duis lacus ante, laoreet hendrerit vestibulum vel, sagittis sed ex. Aliquam condimentum eros vel sollicitudin commodo. Nulla vitae arcu eget ante vestibulum semper. Proin non sapien ultrices, facilisis diam non, faucibus magna. Ut ipsum augue, hendrerit eget mauris quis, volutpat tincidunt ante. Sed quis semper magna, eget interdum nisi.
Duis sollicitudin ultricies velit, non scelerisque arcu eleifend ut. Maecenas in auctor eros. In ac lacus quis erat dapibus hendrerit. Praesent efficitur leo velit, sed porta tortor euismod tempus. Suspendisse efficitur auctor vehicula. Donec dui quam, ultricies non metus vulputate, vehicula vehicula massa. Proin semper ante vel est pretium, vel eleifend arcu mollis.
Suspendisse vel odio id ligula sodales tempor. Duis sed ante eget risus eleifend dapibus quis sit amet nisi. Donec tempor ipsum eros, ut hendrerit est malesuada quis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla eget posuere lacus. Quisque nec turpis nisi. Integer interdum faucibus luctus. Aliquam euismod vehicula fringilla. Aenean nisi velit, dictum vel dolor sit amet, bibendum feugiat nisi. Curabitur mattis mauris sed elit viverra elementum. Maecenas euismod dignissim neque, sed dictum dolor porta ut. Nam euismod dui in mauris sagittis, nec vehicula purus fringilla.
Curabitur interdum tellus facilisis, commodo orci et, molestie lectus. Mauris sagittis sapien eget lacus pellentesque vestibulum. Suspendisse tincidunt varius tortor id aliquet. Suspendisse ultrices congue ultricies. Sed volutpat dui non nisl molestie, nec semper quam ultricies. Aenean posuere, est at iaculis scelerisque, ante magna hendrerit mauris, vel cursus lectus tortor ac mauris. Duis in dolor risus. Vestibulum ut nisi eu ipsum egestas blandit. Nullam mattis id felis et vulputate. Nunc id nunc a tortor mollis ultricies. Suspendisse potenti.
Vivamus tempor pellentesque congue. Cras dapibus accumsan erat. Aenean a lobortis tellus. Aenean massa enim, feugiat et tincidunt eu, interdum a ligula. Integer nec dapibus mi. Nulla venenatis justo vitae turpis porttitor maximus. Maecenas molestie blandit ligula a fermentum. Pellentesque rhoncus risus ut eleifend semper. Cras sed velit id leo fringilla pharetra eu eget nibh. Pellentesque quis tempus lorem. Nulla finibus, nisl ut maximus faucibus, ligula ante pulvinar nibh, ac aliquet leo augue at ligula. Sed lobortis tellus id dolor commodo, ut auctor turpis porta.
Quisque bibendum turpis at elit semper facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam suscipit nisl sapien, eget pulvinar nunc varius ac. Ut rhoncus arcu non turpis aliquet hendrerit. Nulla faucibus elementum urna vel porttitor. Phasellus auctor diam vel lorem vulputate, eu posuere neque varius. Curabitur a congue velit, a euismod ex. Fusce in lobortis quam. Vivamus in sagittis dui. Suspendisse eleifend arcu eget sagittis condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas maximus dui nec velit blandit interdum. Aliquam eleifend ex non magna rutrum, at pulvinar erat porta. Integer bibendum eget orci a volutpat.
Aliquam nec turpis a sem varius pretium. Nulla facilisi. Aenean ipsum dolor, dictum vel nisl at, eleifend dignissim enim. Curabitur ut commodo dui, non mollis velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum et mi maximus, mollis nisl et, fermentum lacus. Suspendisse ligula urna, lacinia a accumsan ut, tincidunt sed tortor. Duis non fringilla orci. Duis lacinia, sem non eleifend tempor, nibh lacus facilisis est, sit amet dictum odio odio non enim. Duis quis laoreet enim. Sed sed ipsum sit amet sem suscipit vehicula id id enim. Integer quis tortor ut magna fringilla sagittis. Nam posuere faucibus velit ac dignissim. Nulla facilisi.
Vestibulum enim mauris, tristique sit amet gravida sit amet, pulvinar ut leo. Proin suscipit imperdiet scelerisque. Vivamus varius porttitor turpis. Quisque ut enim vitae justo tincidunt gravida eget ut erat. Etiam hendrerit, augue sed consequat vehicula, massa lacus euismod augue, at suscipit sapien arcu non purus. Nunc lectus eros, tempor at cursus id, iaculis in lorem. Aliquam et cursus urna. Phasellus nunc lacus, commodo vel vestibulum ut, congue non dolor. Mauris eleifend faucibus molestie. Duis est turpis, accumsan ut ante a, eleifend varius nibh. Etiam sed nibh venenatis, luctus sapien sit amet, hendrerit eros. Vivamus pretium elementum libero in mattis. Aliquam egestas velit sed scelerisque viverra. In libero sem, cursus et neque vitae, semper suscipit turpis. Sed vitae vehicula elit, in egestas elit. Sed varius nibh et turpis tempor iaculis.
Morbi congue porttitor augue, eu ornare dui scelerisque sed. Nunc vel commodo nibh, eu condimentum tellus. Vestibulum sem sapien, fermentum auctor tempus sed, auctor vel dolor. Fusce ac interdum arcu, non tincidunt enim. Donec consectetur odio nibh, ac vestibulum enim elementum at. Sed tortor nibh, ullamcorper quis condimentum vitae, sodales id libero. Sed a nisi et purus iaculis faucibus. Curabitur quis enim porta, congue nunc ut, aliquam libero. Donec viverra ante sed justo dignissim pulvinar. Maecenas diam libero, consequat sed felis id, euismod pellentesque libero. Fusce finibus, mauris nec molestie facilisis, ligula purus facilisis sem, in sodales turpis nibh in eros. Cras ultrices lobortis urna, vel faucibus mauris pulvinar lacinia.
Integer quis felis urna. Sed euismod dui ut convallis sollicitudin. Vivamus sollicitudin lacus nec justo condimentum semper. Sed eget accumsan urna. Quisque varius nulla orci, ac condimentum ligula vestibulum at. Curabitur rhoncus magna at mauris viverra congue. Morbi eu erat vel arcu euismod consectetur sed id elit. Sed mattis dolor ut varius pellentesque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque imperdiet, sem at dapibus varius, tellus justo ullamcorper orci, a consectetur dui dolor a enim.
Nulla aliquam nunc eu dolor venenatis, sit amet maximus ipsum ullamcorper. Sed vitae sollicitudin ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse bibendum purus et efficitur sodales. Mauris efficitur, mi pellentesque aliquam maximus, dolor neque volutpat eros, vitae ornare lectus libero non elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dapibus elementum odio, id viverra libero convallis id. Ut porttitor posuere nisi, sed venenatis erat auctor dapibus. Vivamus mauris mauris, eleifend nec lectus vitae, accumsan lobortis nunc. Nunc tempor, lectus condimentum vestibulum congue, purus libero interdum libero, vel finibus ipsum orci sit amet nulla. Aliquam nec tristique felis. Sed rutrum felis quis porta sodales.
Praesent pellentesque libero at tortor imperdiet luctus. Sed volutpat convallis ipsum at tristique. Nam ex mi, congue sed arcu sit amet, egestas blandit nisi. Phasellus ornare nisi nec justo mattis, vitae consectetur erat imperdiet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non dui rhoncus, maximus diam non, commodo neque. Fusce a quam quam.
Aenean interdum sed libero quis mollis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin nisl libero, suscipit nec faucibus vitae, volutpat at augue. Quisque sit amet metus vulputate, pulvinar libero nec, imperdiet est. Quisque pellentesque aliquet ipsum consectetur hendrerit. Sed augue orci, venenatis sit amet ipsum quis, fringilla porttitor diam. Nam blandit sagittis molestie.
Nam tristique imperdiet sollicitudin. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed ultricies dolor nisi, nec semper felis semper sed. Mauris turpis lacus, maximus nec ex nec, ultrices consequat nisi. Aenean placerat neque vitae viverra blandit. Maecenas sed tristique est. Suspendisse posuere sagittis rhoncus. Donec suscipit odio quis velit viverra, at tristique odio cursus. Proin sollicitudin, felis at vestibulum ultrices, eros ante posuere ante, nec tincidunt nisl orci sed nunc. Nulla facilisi. Sed eget fermentum turpis. Cras varius, arcu tempor vestibulum pharetra, dui ligula fringilla lorem, id ullamcorper tellus eros ac ex. Cras pretium ultrices iaculis. Praesent vel leo suscipit, gravida felis at, fermentum mi. Ut sem nisl, tristique eu aliquet tristique, venenatis sit amet erat. Cras vehicula leo enim, in dapibus est mollis faucibus.
Cras et elementum tellus. Donec at nisl neque. Proin est tortor, maximus sit amet lacus et, suscipit fringilla nisi. Nulla commodo, neque vel rutrum congue, massa leo imperdiet justo, sit amet tincidunt nunc nulla nec justo. Etiam suscipit tristique gravida. Curabitur cursus maximus massa. Nullam commodo enim eget auctor hendrerit.
Nullam eleifend rhoncus diam. Proin ut dolor tellus. Sed dictum tempor nunc, nec porta lectus ullamcorper a. Donec feugiat placerat ligula. Donec vitae est sollicitudin, ullamcorper tellus nec, placerat tellus. Suspendisse pharetra est turpis, eu ultricies lorem auctor vitae. Pellentesque scelerisque nunc tempus mi placerat, sed pretium felis faucibus. Curabitur sed pretium dolor.
Vestibulum convallis lectus magna, eu posuere felis ullamcorper at. Ut pretium posuere ipsum, sit amet aliquam ante dictum id. Aliquam pulvinar sagittis libero vitae interdum. Sed ut mi sit amet augue tempor volutpat in ut eros. Vestibulum dictum ipsum ornare, aliquet eros sed, consectetur nisi. Donec et urna non felis porttitor ornare nec id diam. Vivamus at lacus sapien. Vivamus ac tellus vel est volutpat lobortis. Morbi iaculis neque vel vulputate ultrices. Nam egestas a dui at faucibus. Donec a augue euismod, dignissim arcu id, dictum turpis. Pellentesque quis quam eu est luctus ornare. Nam rutrum leo ex, et consectetur tortor iaculis nec. Cras posuere ligula sit amet quam dapibus, vel sagittis ex vehicula. Suspendisse quam ipsum, laoreet vel tristique eget, vehicula nec tortor. Nunc semper, erat id sagittis interdum, velit eros tincidunt lectus, vitae gravida arcu erat in velit.`;

export const loremWords = (count) => {
  return text.split(/\s/).slice(0, count).join(" ");
};

export const loremSentences = (count) => {
  return text.split(".").slice(0, count).join(".") + ".";
};

export const htmlAttrs = ({
  checked,
  className,
  disabled,
  id,
  placeholder,
  readonly,
  rows,
  type,
  value,
}: {
  checked?: boolean;
  className?: string;
  disabled?: boolean;
  id?: string;
  placeholder?: string;
  readonly?: boolean;
  rows?: number;
  type?: string;
  value?: string;
}) => {
  const attrs: string[] = [];

  if (checked) attrs.push("checked");
  if (className) attrs.push(`class="${className}"`);
  if (disabled) attrs.push("disabled");
  if (id) attrs.push(`id="${id}"`);
  if (placeholder) attrs.push(`placeholder="${placeholder}"`);
  if (readonly) attrs.push("readonly");
  if (type) attrs.push(`type="${type}"`);
  if (value) attrs.push(`value="${value}"`);
  if (rows) attrs.push(`rows="${rows}"`);

  return attrs.join(" ");
};
